#!/bin/bash
#/etc/init.d/zookeeper
DAEMON_PATH=/opt/kafka/bin
DAEMON_NAME=zookeeper
ZOOKEEPER_CONFIG=/opt/kafka/config/zookeeper.properties
# Check that networking is up.
#[ ${NETWORKING} = "no" ] && exit 0

PATH=$PATH:$DAEMON_PATH

configure() {
    readarray -t configuration < <(compgen  -A variable | grep "ZOOKEEPER__")
    for variable in "${configuration[@]}"
    do
      zookeeper_parameter="${variable//ZOOKEEPER__/}"
      zookeeper_parameter="${zookeeper_parameter,,}"
      zookeeper_parameter="${zookeeper_parameter//_/\.}"
      eval value=\$$variable
      if [ "`grep $zookeeper_parameter $ZOOKEEPER_CONFIG | grep '^[^#;]'`" == "" ]; then
        echo -e "\n$zookeeper_parameter=$value\n" >> $ZOOKEEPER_CONFIG
      else
        sed -r -i "s/#($zookeeper_parameter)=(.*)/\1=$value/g" $ZOOKEEPER_CONFIG
      fi
    done
}

# See how we were called.
case "$1" in
  start)
        # Start daemon.
        configure
        pid=`ps ax | grep -i 'org.apache.zookeeper' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
            echo "Zookeeper is already running";
        else
          echo "Starting $DAEMON_NAME";
          $DAEMON_PATH/zookeeper-server-start.sh -daemon $ZOOKEEPER_CONFIG
        fi
        ;;
  stop)
        echo "Shutting down $DAEMON_NAME";
        $DAEMON_PATH/zookeeper-server-stop.sh
        ;;
  restart)
        $0 stop
        sleep 2
        $0 start
        ;;
  status)
        pid=`ps ax | grep -i 'org.apache.zookeeper' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
          echo "Zookeeper is Running as PID: $pid"
        else
          echo "Zookeeper is not Running"
        fi
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
