#!/usr/bin/env bash

SCALA_VERSIONS=( "2.11" "2.12" )
KAFKA_VERSIONS=( "1.0.0" "1.1.0" "2.0.0" )

for SCALA_VERSION in "${SCALA_VERSIONS[@]}"
do
    for KAFKA_VERSION in "${KAFKA_VERSIONS[@]}"
    do
        $IMAGE_NAME="$DOCKER_REPO:$SCALA_VERSION-$KAFKA_VERSION"
        docker build --build-arg=SCALA_VERSION=$SCALA_VERSION --build-arg=KAFKA_VERSION=$KAFKA_VERSION -t $IMAGE_NAME .
        docker push $IMAGE_NAME
    done
done
