#!/usr/bin/env bash

SCALA_VERSIONS=( "2.11" "2.12" )
KAFKA_VERSIONS=( "2.1.1" "2.2.0" "2.2.1" "2.3.0" "2.3.1" )

for SCALA_VERSION in "${SCALA_VERSIONS[@]}"
do
    for KAFKA_VERSION in "${KAFKA_VERSIONS[@]}"
    do
        BUILD="$DOCKER_REPO:$SCALA_VERSION-$KAFKA_VERSION"
        docker build --build-arg=SCALA_VERSION=$SCALA_VERSION --build-arg=KAFKA_VERSION=$KAFKA_VERSION -t $BUILD .
        docker push $BUILD
    done
done
